# Generated by Django 6.0.3 on 2026-05-04 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_mealregenerationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mealregenerationlog",
            index=models.Index(
                fields=["diet_plan", "created_at", "is_undone"],
                name="regen_log_ratelimit_idx",
            ),
        ),
    ]
